version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      MYSQL_DATABASE: dreamcraze
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3307:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

  mysqldb_discount:
    container_name: mysqldb_discount
    image: mysql:latest
    environment:
      MYSQL_DATABASE: discount
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3309:3306
    volumes:
      - ./mysql-data-discount:/var/lib/mysql
    networks:
      - app-network

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./dreamcraze
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    depends_on:
      - mysqldb
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/dreamcraze
      - spring.datasource.username=root
      - spring.datasource.password=123456
    networks:
      - app-network
    restart: on-failure

  discount:
    container_name: discount
    build:
      context: ./discount
      dockerfile: Dockerfile
    ports:
      - 8086:8086
    depends_on:
      - mysqldb_discount
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb_discount:3306/discount
      - spring.datasource.username=root
      - spring.datasource.password=123456
    networks:
      - app-network
    restart: on-failure
  
  frontend-app:
    build:
      context: ./e-commerce
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
