
FROM openjdk:17-jdk-slim AS build
COPY target/dreamcraze-0.0.1-SNAPSHOT.jar dreamcraze-0.0.1-SNAPSHOT.jar
EXPOSE 8090
ENTRYPOINT ["java","-jar","dreamcraze-0.0.1-SNAPSHOT.jar"]














































# FROM openjdk:17-jdk-slim AS build
# Add target/dreamcraze-0.0.1-SNAPSHOT.jar dreamcraze-0.0.1-SNAPSHOT.jar
# EXPOSE 8090
# ENTRYPOINT ["java","-jar","dreamcraze-0.0.1-SNAPSHOT.jar"]
